### ISSUE TITLE
Cannot install on node 5.10.0 or 6.4.0

### ISSUE THREAD

**Issue by OKNoah** [btrask/node-socketwatcher#13]
Tested these two versions so far, so far neither work. Does anyone know the last supported version or an alternative package that is maintained?

```
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
In file included from ../socket_watcher.cpp:5:
In file included from ../socket_watcher.hpp:8:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:181:66: error: too many
      arguments to function call, expected at most 2, have 4
  return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
         ~~~~~~~~~~~~~~~~~~                                      ^~~~~~~~~~
/Users/my-user/.node-gyp/6.4.0/include/node/v8.h:4798:3: note: 'New' declared
      here
  static Local<Signature> New(
  ^
In file included from ../socket_watcher.cpp:5:
In file included from ../socket_watcher.hpp:8:
../node_modules/nan/nan.h:171:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:166:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../node_modules/nan/nan.h:317:12: error: no matching function for call to
      '_NanEnsureLocal'
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:303:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                          ^~~~~~~~~~~~~~~
../node_modules/nan/nan.h:171:25: note: candidate template ignored:
      substitution failure [with T = v8::Primitive]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:322:12: error: no matching function for call to
      '_NanEnsureLocal'
    return NanEscapeScope(NanNew(v8::Null(v8::Isolate::GetCurrent())));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:303:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                          ^~~~~~~~~~~~~~~
../node_modules/nan/nan.h:171:25: note: candidate template ignored:
      substitution failure [with T = v8::Primitive]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:327:12: error: no matching function for call to
      '_NanEnsureLocal'
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:303:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                          ^~~~~~~~~~~~~~~
../node_modules/nan/nan.h:171:25: note: candidate template ignored:
      substitution failure [with T = v8::Boolean]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:332:12: error: no matching function for call to
      '_NanEnsureLocal'
    return NanEscapeScope(NanNew(v8::False(v8::Isolate::GetCurrent())));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:303:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                          ^~~~~~~~~~~~~~~
../node_modules/nan/nan.h:171:25: note: candidate template ignored:
      substitution failure [with T = v8::Boolean]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:376:20: error: no type named 'GCEpilogueCallback' in
      'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:382:20: error: no type named 'GCEpilogueCallback' in
      'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:387:20: error: no type named 'GCPrologueCallback' in
      'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:393:20: error: no type named 'GCPrologueCallback' in
      'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:564:13: error: no member named 'smalloc' in
      namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:575:12: error: no matching function for call to
      'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/my-user/.node-gyp/6.4.0/include/node/node_buffer.h:46:40: note: candidate
      function not viable: 2nd argument ('const char *') would lose const
      qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/my-user/.node-gyp/6.4.0/include/node/node_buffer.h:34:40: note: candidate
      function not viable: no known conversion from 'const char *' to
      'v8::Local<v8::String>' for 2nd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/my-user/.node-gyp/6.4.0/include/node/node_buffer.h:31:40: note: candidate
      function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_...
                                       ^
/Users/my-user/.node-gyp/6.4.0/include/node/node_buffer.h:39:40: note: candidate
      function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../socket_watcher.cpp:5:
In file included from ../socket_watcher.hpp:8:
../node_modules/nan/nan.h:579:12: error: no viable conversion from returned
      value of type 'v8::MaybeLocal<v8::Object>' to function return type
      'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/my-user/.node-gyp/6.4.0/include/node/v8.h:216:7: note: candidate
      constructor (the implicit copy constructor) not viable: no known
      conversion from 'v8::MaybeLocal<v8::Object>' to 'const
      v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/my-user/.node-gyp/6.4.0/include/node/v8.h:216:7: note: candidate
      constructor (the implicit move constructor) not viable: no known
      conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>
      &&' for 1st argument
/Users/my-user/.node-gyp/6.4.0/include/node/v8.h:220:13: note: candidate template
      ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
In file included from ../socket_watcher.cpp:5:
In file included from ../socket_watcher.hpp:8:
../node_modules/nan/nan.h:586:26: error: no member named 'Use' in namespace
      'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
../node_modules/nan/nan.h:1403:12: error: no matching function for call to
      '_NanEnsureLocal'
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:303:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                          ^~~~~~~~~~~~~~~
../node_modules/nan/nan.h:171:25: note: candidate template ignored:
      substitution failure [with T = v8::Function]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:1452:12: error: no matching function for call to
      '_NanEnsureLocal'
    return NanEscapeScope(node::MakeCallback(
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:303:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                          ^~~~~~~~~~~~~~~
../node_modules/nan/nan.h:171:25: note: candidate template ignored:
      substitution failure [with T = v8::Value]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:1522:12: error: no matching function for call to
      '_NanEnsureLocal'
    return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:303:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                          ^~~~~~~~~~~~~~~
../node_modules/nan/nan.h:171:25: note: candidate template ignored:
      substitution failure [with T = v8::Object]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
17 errors generated.
make: *** [Release/obj.target/socketwatcher/socket_watcher.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/my-user/.nvm/versions/v6.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/Users/my-user/.nvm/versions/v6.4.0/bin/node" "/Users/my-user/.nvm/versions/v6.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/my-user/Documents/dev/my-project/node_modules/socketwatcher
gyp ERR! node -v v6.4.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/ansi-regex/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/ansi-styles/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/asn1/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/assert-plus/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/aws-sign2/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/aws4/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/boom/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/caseless/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/combined-stream/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/commander/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/cryptiles/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/core-util-is/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/delayed-stream/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/dashdash/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/ecc-jsbn/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/ctype/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/escape-string-regexp/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/extend/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/extsprintf/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/forever-agent/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/generate-function/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/generate-object-property/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/get-stdin/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/getpass/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/git-config-path/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/graceful-readlink/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/has-ansi/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/hoek/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/infinity-agent/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/inherits/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/ini/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/is-property/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/is-stream/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/is-typedarray/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/isarray/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/isstream/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/jodid25519/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/jsbn/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/json-schema/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/my-user/Documents/dev/my-project/node_modules/json-stringify-safe/package.json'
npm WARN eslint-config-airbnb@10.0.1 requires a peer of eslint-plugin-import@^1.13.0 but none was installed.
npm WARN eslint-config-airbnb@10.0.1 requires a peer of eslint-plugin-jsx-a11y@^2.1.0 but none was installed.
npm WARN eslint-config-airbnb@10.0.1 requires a peer of eslint-plugin-react@^6.0.0 but none was installed.
npm WARN eslint-config-airbnb-base@5.0.3 requires a peer of eslint-plugin-import@^1.13.0 but none was installed.
npm WARN nms-cartographer@0.1.0 No repository field.
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/my-user/.nvm/versions/v6.4.0/bin/node" "/Users/my-user/.nvm/versions/v6.4.0/bin/npm" "install" "--save" "pcap"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! socketwatcher@0.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the socketwatcher@0.2.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the socketwatcher package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs socketwatcher
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls socketwatcher
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/my-user/Documents/dev/my-project/npm-debug.log
npm ERR! code 1
```

**Comment by DarkKnight1992** [comment]
I have same issue, did you found any solution yet ?
