### ISSUE TITLE
Issues compiling with Node v10+

### ISSUE THREAD

**Issue by sumeetkpatel** [btrask/node-socketwatcher#18]
I am having an issue compiling this package with Node v10+, on the other hand the stable Node 8.11.2 is still working fine.

I believe some of these v8 and Nan usages are now deprecated.

```
> socketwatcher@0.3.0 install /path/node_modules/socketwatcher
> node-gyp rebuild

make: Entering directory '/path/node_modules/socketwatcher/build'
  CXX(target) Release/obj.target/socketwatcher/socket_watcher.o
../socket_watcher.cpp: In static member function ‘static void SocketWatcher::Callback(uv_poll_t*, int, int)’:
../socket_watcher.cpp:77:60: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
   Nan::MakeCallback(watcher->handle(), callback, argc, argv);
                                                            ^
In file included from ../socket_watcher.hpp:8:0,
                 from ../socket_watcher.cpp:5:
../../nan/nan.h:929:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^
../socket_watcher.cpp: In static member function ‘static void SocketWatcher::New(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../socket_watcher.cpp:104:49: error: no matching function for call to ‘v8::Function::NewInstance()’
     info.GetReturnValue().Set(cons->NewInstance());
                                                 ^
In file included from /home/user/.node-gyp/10.2.1/include/node/node.h:63:0,
                 from ../../nan/nan.h:51,
                 from ../socket_watcher.hpp:8,
                 from ../socket_watcher.cpp:5:
/home/user/.node-gyp/10.2.1/include/node/v8.h:3859:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>, int, v8::Local<v8::Value>*) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^
/home/user/.node-gyp/10.2.1/include/node/v8.h:3859:44: note:   candidate expects 3 arguments, 0 provided
/home/user/.node-gyp/10.2.1/include/node/v8.h:3862:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^
/home/user/.node-gyp/10.2.1/include/node/v8.h:3862:44: note:   candidate expects 1 argument, 0 provided
socketwatcher.target.mk:95: recipe for target 'Release/obj.target/socketwatcher/socket_watcher.o' failed
make: *** [Release/obj.target/socketwatcher/socket_watcher.o] Error 1
make: Leaving directory '/path/node_modules/socketwatcher/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/n/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.4.0-62-generic
gyp ERR! command "/home/user/n/bin/node" "/home/user/n/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /path/node_modules/socketwatcher
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

**Comment by jupe** [comment]
I have same issue. Would like to get fix for this.

**Comment by frankjoke** [comment]
I have same issue and because my application need to run on many different versions from node 4.3 upwards I cannot use the package then!
