### ISSUE TITLE
npm install fails on >=iojs-2.2.x

### ISSUE THREAD

**Issue by thomasfr** [btrask/node-socketwatcher#8]
```
$ node -v
v2.3.0
$ npm install socketwatcher --save

> socketwatcher@0.2.0 install /Users/thomas/node_modules/socketwatcher
> node-gyp rebuild

  CXX(target) Release/obj.target/socketwatcher/socket_watcher.o
In file included from ../socket_watcher.cpp:4:
../socket_watcher.hpp:7:36: error: expected class name
class SocketWatcher : public node::ObjectWrap {
                                   ^
../socket_watcher.hpp:14:9: error: unknown type name 'uv_poll_t'
        uv_poll_t* poll_;
        ^
../socket_watcher.hpp:18:48: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> New(const v8::Arguments & args);
                                               ^~~~~~~~~~~~~
                                               v8::internal::Arguments
/Users/thomas/.node-gyp/2.3.0/deps/v8/include/v8.h:134:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../socket_watcher.cpp:4:
../socket_watcher.hpp:19:48: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> Set(const v8::Arguments & args);
                                               ^~~~~~~~~~~~~
                                               v8::internal::Arguments
/Users/thomas/.node-gyp/2.3.0/deps/v8/include/v8.h:134:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../socket_watcher.cpp:4:
../socket_watcher.hpp:20:50: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> Start(const v8::Arguments& args);
                                                 ^~~~~~~~~~~~~
                                                 v8::internal::Arguments
/Users/thomas/.node-gyp/2.3.0/deps/v8/include/v8.h:134:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../socket_watcher.cpp:4:
../socket_watcher.hpp:21:49: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> Stop(const v8::Arguments& args);
                                                ^~~~~~~~~~~~~
                                                v8::internal::Arguments
/Users/thomas/.node-gyp/2.3.0/deps/v8/include/v8.h:134:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../socket_watcher.cpp:4:
../socket_watcher.hpp:25:30: error: unknown type name 'uv_poll_t'
        static void Callback(uv_poll_t *w, int status, int events);
                             ^
../socket_watcher.cpp:39:31: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> Calleback(const Arguments& args) {
                              ^~~~~~~~~
                              v8::internal::Arguments
/Users/thomas/.node-gyp/2.3.0/deps/v8/include/v8.h:134:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../socket_watcher.cpp:40:12: error: no matching function for call to 'Undefined'
    return Undefined();
           ^~~~~~~~~
/Users/thomas/.node-gyp/2.3.0/deps/v8/include/v8.h:327:28: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
  friend Handle<Primitive> Undefined(Isolate* isolate);
                           ^
../socket_watcher.cpp:47:55: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of type 'v8::Handle<v8::Value> (const v8::internal::Arguments &)'
    Local<FunctionTemplate> t = FunctionTemplate::New(New);
                                                      ^~~
/Users/thomas/.node-gyp/2.3.0/deps/v8/include/v8.h:3871:16: note: passing argument to parameter 'isolate' here
      Isolate* isolate,
               ^
../socket_watcher.cpp:49:29: error: no member named 'NewSymbol' in 'v8::String'
    t->SetClassName(String::NewSymbol("SocketWatcher"));
                    ~~~~~~~~^
../socket_watcher.cpp:52:41: error: cannot initialize a parameter of type 'v8::FunctionCallback' (aka 'void (*)(const FunctionCallbackInfo<v8::Value> &)') with an lvalue of type
      'v8::Handle<v8::Value> (const v8::internal::Arguments &)': type mismatch at 1st parameter ('const FunctionCallbackInfo<v8::Value> &' vs 'const v8::internal::Arguments &')
    NODE_SET_PROTOTYPE_METHOD(t, "set", SocketWatcher::Set);
                                        ^~~~~~~~~~~~~~~~~~
/Users/thomas/.node-gyp/2.3.0/src/node.h:254:60: note: passing argument to parameter 'callback' here
                                      v8::FunctionCallback callback) {
                                                           ^
../socket_watcher.cpp:53:43: error: address of overloaded function 'Start' does not match required type 'void (const v8::FunctionCallbackInfo<v8::Value> &)'
    NODE_SET_PROTOTYPE_METHOD(t, "start", SocketWatcher::Start);
                                          ^~~~~~~~~~~~~~~~~~~~
../socket_watcher.hpp:20:38: note: candidate function has type mismatch at 1st parameter (expected 'const v8::FunctionCallbackInfo<v8::Value> &' but has 'const v8::internal::Arguments &')
        static v8::Handle<v8::Value> Start(const v8::Arguments& args);
                                     ^
../socket_watcher.hpp:23:14: note: candidate function has different number of parameters (expected 1 but has 0)
        void Start();
             ^
/Users/thomas/.node-gyp/2.3.0/src/node.h:254:60: note: passing argument to parameter 'callback' here
                                      v8::FunctionCallback callback) {
                                                           ^
../socket_watcher.cpp:54:42: error: address of overloaded function 'Stop' does not match required type 'void (const v8::FunctionCallbackInfo<v8::Value> &)'
    NODE_SET_PROTOTYPE_METHOD(t, "stop", SocketWatcher::Stop);
                                         ^~~~~~~~~~~~~~~~~~~
../socket_watcher.hpp:21:38: note: candidate function has type mismatch at 1st parameter (expected 'const v8::FunctionCallbackInfo<v8::Value> &' but has 'const v8::internal::Arguments &')
        static v8::Handle<v8::Value> Stop(const v8::Arguments& args);
                                     ^
../socket_watcher.hpp:24:14: note: candidate function has different number of parameters (expected 1 but has 0)
        void Stop();
             ^
/Users/thomas/.node-gyp/2.3.0/src/node.h:254:60: note: passing argument to parameter 'callback' here
                                      v8::FunctionCallback callback) {
                                                           ^
../socket_watcher.cpp:56:25: error: no member named 'NewSymbol' in 'v8::String'
    target->Set(String::NewSymbol("SocketWatcher"), t->GetFunction());
                ~~~~~~~~^
../socket_watcher.cpp:58:23: error: use of undeclared identifier 'NODE_PSYMBOL'
    callback_symbol = NODE_PSYMBOL("callback");
                      ^
../socket_watcher.cpp:61:42: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> SocketWatcher::Start(const Arguments& args) {
                                         ^~~~~~~~~
                                         v8::internal::Arguments
/Users/thomas/.node-gyp/2.3.0/deps/v8/include/v8.h:134:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../socket_watcher.cpp:62:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/thomas/.node-gyp/2.3.0/deps/v8/include/v8.h:869:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../socket_watcher.cpp:63:30: error: use of undeclared identifier 'ObjectWrap'
    SocketWatcher *watcher = ObjectWrap::Unwrap<SocketWatcher>(args.Holder());
                             ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/socketwatcher/socket_watcher.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/thomas/.nvm/versions/io.js/v2.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "/Users/thomas/.nvm/versions/io.js/v2.3.0/bin/iojs" "/Users/thomas/.nvm/versions/io.js/v2.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/thomas/node_modules/socketwatcher
gyp ERR! node -v v2.3.0
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Darwin 14.4.0
npm ERR! argv "/Users/thomas/.nvm/versions/io.js/v2.3.0/bin/iojs" "/Users/thomas/.nvm/versions/io.js/v2.3.0/bin/npm" "install" "socketwatcher" "--save"
npm ERR! node v2.3.0
npm ERR! npm  v2.11.1
npm ERR! code ELIFECYCLE

npm ERR! socketwatcher@0.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the socketwatcher@0.2.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the socketwatcher package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls socketwatcher
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/thomas/npm-debug.log
```

**Comment by ChALkeR** [comment]
Adding to the list: https://github.com/nodejs/node/issues/2798.
